services:
  retail_bot:
    build: .
    restart: unless-stopped
    command: [ "/bin/sh", "-c", "/app/start_bot.sh" ]
    env_file:
      - .env
    volumes:
      - ./whisper_cache:/root/.cache/whisper # Сохранение модели whisper, чтобы не скачивать при каждом перезапуске
    networks:
      - infra-net
volumes:
  mysql_db:

networks:
  infra-net:
    name: infra-net-${CONTOUR}
    external: true

